
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 653052
	#The name of the modpack
	modpackName = "TechAttack"
	#The version of the modpack
	modpackVersion = "1.0.0"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = true

