
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Allows the mod to try to remap and convert other blocks and items from other compat mods that have been uninstalled from one world. This was made so one can uninstall such mods seamlessly having their blocks converted into Evety Compat counterparts
	remap_other_mods = true
	#Clears out and remaps all blocks registered by this mod belonging to uninstalled wood types to air or oak wood
	remap_self = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true

[leaves_type]

	[leaves_type.minecraft]
		oak = true
		spruce = true
		birch = true
		jungle = true
		acacia = true
		dark_oak = true
		azalea = true
		flowering_azalea = true

	[leaves_type.fruittrees]
		cherry = true
		redlove = true
		mandarin = true
		lime = true
		citron = true
		pomelo = true
		orange = true
		lemon = true
		grapefruit = true
		apple = true

	[leaves_type.integrateddynamics]
		menril = true

	[leaves_type.blue_skies]
		bluebright = true
		starlit = true
		frostbright = true
		lunar = true
		dusk = true
		maple = true
		cherry = true
		crescent_fruit = true

	[leaves_type.malum]
		runewood = true
		soulwood = true

	[leaves_type.biomesoplenty]
		fir = true
		redwood = true
		mahogany = true
		jacaranda = true
		palm = true
		willow = true
		dead = true
		magic = true
		umbran = true
		hellbark = true
		origin = true
		flowering_oak = true
		rainbow_birch = true
		yellow_autumn = true
		orange_autumn = true
		maple = true
		white_cherry = true
		pink_cherry = true

	[leaves_type.tconstruct]
		earth_slime = true
		sky_slime = true
		ender_slime = true

	[leaves_type.quark]
		blue_blossom = true
		lavender_blossom = true
		orange_blossom = true
		pink_blossom = true
		yellow_blossom = true
		red_blossom = true

	[leaves_type.ars_nouveau]
		blue_archwood = true
		red_archwood = true
		green_archwood = true
		purple_archwood = true

	[leaves_type.ars_elemental]
		yellow_archwood = true

	[leaves_type.dynamictrees]
		spruce = true
		oak = true
		jungle = true
		dark_oak = true
		birch = true
		acacia = true

	[leaves_type.dtbop]
		yellow_autumn = true
		willow = true
		white_cherry = true
		umbran = true
		spruce_twiglet = true
		spruce_poplar = true
		sparse_oak = true
		sparse_acacia = true
		redwood = true
		rainbow_birch = true
		poplar = true
		pink_cherry = true
		palm = true
		orange_autumn = true
		oak_twiglet = true
		mega_dark_oak = true
		maple_twiglet = true
		maple = true
		mahogany = true
		magic_poplar = true
		jungle_twiglet = true
		jacaranda = true
		hellbark_bush = true
		hellbark = true
		flowering_oak = true
		fir = true
		dying = true
		dark_poplar = true
		dark_oak_twiglet = true
		cypress_willow = true
		acacia_twiglet = true

[wood_type]

	[wood_type.minecraft]
		oak = true
		spruce = true
		birch = true
		jungle = true
		acacia = true
		dark_oak = true
		crimson = true
		warped = true

	[wood_type.fruittrees]
		cherry = true
		citrus = true

	[wood_type.integrateddynamics]
		menril = true

	[wood_type.blue_skies]
		bluebright = true
		starlit = true
		frostbright = true
		lunar = true
		dusk = true
		maple = true
		cherry = true

	[wood_type.tconstruct]
		greenheart = true
		skyroot = true
		bloodshroom = true

	[wood_type.quark]
		azalea = true
		blossom = true

	[wood_type.malum]
		runewood = true
		soulwood = true

	[wood_type.biomesoplenty]
		fir = true
		redwood = true
		cherry = true
		mahogany = true
		jacaranda = true
		palm = true
		willow = true
		dead = true
		magic = true
		umbran = true
		hellbark = true

	[wood_type.botania]
		livingwood = true
		dreamwood = true

