
["Shield mechanics settings"]
	#List of shield items and their damage values. Start the game once to fill these entries with all modded shields automatically. Format: Shield name id;shield damage reduction on block; shield passive damage reduction when just held.E.g. default: ["minecraft:shield;65;15"] this give the minecraft shield 65% damage reduction on block, and 15% passive damage reduction when not blocking but held.To put multiple values seperate them by commas like this:  ["minecraft:shield;65;15", "minecraft:shield;65;15"] 
	shields = ["blue_skies:moonstone_shield;70;14", "mekanismtools:lapis_lazuli_shield;65;11", "mekanismtools:steel_shield;64;15", "blue_skies:spike_shield;77;12", "twilightforest:knightmetal_shield;72;16", "minecraft:shield;65;15", "mekanismtools:bronze_shield;64;16", "mekanismtools:refined_obsidian_shield;74;18", "ars_nouveau:enchanters_shield;68;14", "mekanismtools:refined_glowstone_shield;61;21", "mekanismtools:osmium_shield;76;10", "immersiveengineering:shield;78;12"]
	#Should the mechanic changes only affect players
	playerOnly = false
	#Should blocking with a shield set it on cooldown(players only), values are in ticks. 20 ticks = 1 sec
	#Range: 0 ~ 100
	blockCooldown = 5
	#Maximum percent of damage allowed to be blocked. Default:85
	#Range: 0 ~ 100
	maxblockdamagereduction = 85
	#Maximum percent of damage reduction while holding a shield(not blocking). Default:25
	#Range: 0 ~ 100
	maxpassivedamagereduction = 25

